### ISSUE TITLE
Requisição HTTP para mandar mensagem

### ISSUE THREAD

**Issue by DevRadhy** [dev-house-community/EarphoneJack#30]
## O que precisa ser feito
Atualizar campos da requisição.

- Aceitar `userId`, para fazer a verificação de permissão
- Atualizar `channel` para `channelId`

O `body` da requisição ficaria da seguinte forma.

```json
{
  "serverId": "573921656813387783",
  "channelId": "847326360619188265",
  "message": "Thaíssa Candella",
  "reactions": ["<:heart:847228111510437919>"]
}
```
**Resultado**
![message](https://user-images.githubusercontent.com/50425715/119848641-5b627e80-bee2-11eb-9ffe-2e87b7e70994.png)

**Comment by jorge-lba** [comment]
Podemos incluir o JWT e a validação se a pessoa tem as permissões para enviar msg no canal nessa issues mesmo?

**Comment by DevRadhy** [comment]
> Podemos incluir o JWT e a validação se a pessoa tem as permissões para enviar msg no canal nessa issues mesmo?

podemos sim
